// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://stfxuwrekxbhkbzfhprq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InN0Znh1d3Jla3hiaGtiemZocHJxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTEyOTM1NTYsImV4cCI6MjA2Njg2OTU1Nn0.4yL8e90mkK_SitK4NsimHjkktuWNAZ4IQYRqD2DnmtQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});